### ISSUE TITLE
ImportError: No module named src.metal_dock.main

### ISSUE THREAD

**Issue by Saem5075** [vvoelz/metaldock_demo#1]
(MetalDock) saem@b0-be-83-3f-26-bb ~ % metaldock -i input.ini 
Traceback (most recent call last):
  File "/Users/saem/MetalDock/metaldock", line 3, in <module>
    from src.metal_dock.main import main
ImportError: No module named src.metal_dock.main

**Comment by vvoelz** [comment]
Hi @Saem5075 -- Thanks for raising this issue.  Issues are a great way to communicate on problem-solving.  

I think what's going on is that the MetalDock author(s) has provided a very weak method for installing the code base, by having us download the source,  and having the $PYTHONPATH environment variable point to it.  This is not the "conda" way of installing/managing packages.  Let me look into some ways to do it better.   I will report back shortly.

**Comment by vvoelz** [comment]
Ok @Saem5075 -- I think I figured out how to successfully install the `metaldock` executable script.  Please see my installation guide in the [README.md](https://github.com/vvoelz/metaldock_demo/blob/main/README.md). Try it out, and let me know.

**Comment by Saem5075** [comment]
Thank you so much! I am trying, and I will let you know the outcome.

**Comment by Saem5075** [comment]
Hi Dr. Voelz,

I tried to follow every step but while run % metaldock -i input.ini following error found. I don't know what is that.

(MetalDock) saem@As-MacBook-Air MetalDock % metaldock -i orca_input.ini
Traceback (most recent call last):
  File "/Users/saem/git/MetalDock/metaldock", line 6, in <module>
    main()
  File "/Users/saem/git/MetalDock/src/metal_dock/main.py", line 18, in main
    docking(par)
  File "/Users/saem/git/MetalDock/src/metal_dock/docking.py", line 66, in docking
    qm_dir, energy = adf.adf_engine(xyz_file, par, output_dir)
  File "/Users/saem/git/MetalDock/src/metal_dock/adf_engine.py", line 25, in adf_engine
    adf_opt_converged('ams.log')
  File "/Users/saem/git/MetalDock/src/metal_dock/adf_engine.py", line 64, in adf_opt_converged
    with open(ams_log) as log:
FileNotFoundError: [Errno 2] No such file or directory: 'ams.log'
